### ISSUE TITLE
Project idea: <Browser Tab System> in <C>

### ISSUE THREAD

**Issue by deVedant** [Atharv-Attri/HacktoberFest-Projects#10]
### C program to make a Web _Browser Tab System_. 
- Add a Tab
- Incognito Tab
- Back
- Add to Bookmarks 
- Recent Tabs
- View Bookmarks
- View History

Basically any basic functioning of a web browser in simple C language. 

Note : There won't be any real time searches as the interaction will be on terminal. 

### Any Browsers like Chrome, Edge, Opera, Firefox

**Sample Output**:

![IMG_20201002_185728.jpg](https://user-images.githubusercontent.com/59828215/94928342-2af84b00-04e1-11eb-9e38-3f5031f5ae27.jpg)

FYI : **Incognito tabs** are not viewed in **History** as in real-time. 
Checklist:
 - [x] This has not been made in the language I want to make it in
- [x] I 100% believe this  meets quality standards

**Comment by Atharv-Attri** [comment]
Sure, go ahead!

**Comment by deVedant** [comment]
> Sure, go ahead!
I need help.
I am using 2 github accounts on my laptop. Hence using SSH keys, but, that doesn't seem to work. I'm stuck. Please help me out.
Here's the screenshot :
![Screenshot 2020-10-03 023421](https://user-images.githubusercontent.com/72208637/94970168-b1348180-0521-11eb-9f4a-dc79cd0ee7ba.png)

**Comment by Atharv-Attri** [comment]
I, unfortunately, don't know how to help with this, I've never used SSH. I recommend you try https://docs.github.com/en or stackoverflow.

**Comment by deVedant** [comment]
> I, unfortunately, don't know how to help with this, I've never used SSH. I recommend you try https://docs.github.com/en or stackoverflow. Sorry I can't be of more help!

Ah, I'll directly make a PR then by uploading .C files. That would do the work. OK????

**Comment by Atharv-Attri** [comment]
If you are 100% everything works properly in your code, sure!
