### ISSUE TITLE
Project idea: <Captain-America -Logo> in <Python-using-turtle-module>

### ISSUE THREAD

**Issue by yashqwerty1** [Atharv-Attri/HacktoberFest-Projects#15]
### What is a usage example of this? (We get somethings are pointless, yet still complex and fun to make, so we won't hold it against you if there is none.)

Checklist:
- [ ]  This has not been made in the language I want to make it in

- [x] I 100% believe this  meets quality standards

**Comment by Atharv-Attri** [comment]
Can you please describe your project?

**Comment by yashqwerty1** [comment]
It will create Captain America Logo Using Python Library/Module - Turtle

**Comment by Atharv-Attri** [comment]
I don't know much about turtle, so if you are 100% sure it will be complex enough go for it!

**Comment by Atharv-Attri** [comment]
I'm excited to see what comes out of this!

**Comment by yashqwerty1** [comment]
Yeah Sure. When I should send a pull request.

**Comment by Atharv-Attri** [comment]
Whenever you have it done!

**Comment by yashqwerty1** [comment]
Ok. Can You review it right now.

**Comment by Atharv-Attri** [comment]
Yes, I can

**Comment by yashqwerty1** [comment]
Wait a minute i will just fork this repo and generate a pull request

**Comment by yashqwerty1** [comment]
Its ready brother you should test it. Its Fun literally

**Comment by Atharv-Attri** [comment]
Nice! I added a comment to your PR, please take care of that and I'll merge!
