### ISSUE TITLE
Project idea: Multi-threading and Networking in Java

### ISSUE THREAD

**Issue by Saif807380** [Atharv-Attri/HacktoberFest-Projects#2]
### Describe your project idea here
The idea is to demonstrate concepts of multi-threading, operating systems and networking using simple Java Programs.

### What is a usage example of this? (We get somethings are pointless, yet still complex and fun to make, so we won't hold it against you if there is none.)

Checklist:
- [ ] Will demonstrate multithreading using bank transaction example.
- [ ] Simulate deadlock and producer-consumer problem.
- [ ] Show interaction between TCP client and multi-threaded TCP server.
- [ ] I 100% believe this meets quality standards

**Comment by Atharv-Attri** [comment]
Love it! Really great idea, meets quality standards. Go for it!
