### ISSUE TITLE
Project idea: BMI Calculator in Python

### ISSUE THREAD

**Issue by junyongxlee** [Atharv-Attri/HacktoberFest-Projects#27]
### Describe your project idea here
The user inputs their weight and height, BMI will be calculated and returned as a result.

### What is a usage example of this? (We get somethings are pointless, yet still complex and fun to make, so we won't hold it against you if there is none.)
Calculate their BMI

Checklist:
- [ Yes] This has not been made in the language I want to make it in
- [ Yes] I 100% believe this  meets quality standards

**Comment by KuruvillaJacob02** [comment]
Has this issue be assigned? If not, it would be much appreciated if this issue was assigned to me

**Comment by Atharv-Attri** [comment]
@KuruvillaJacob02 I assign it to the person who had the idea, unless they explicitly say they don't want to do it. 

@junyongxlee Sure! However, I feel a BMI calculator on its own might be too simple. PLease see if you can find a way to make it more complex. An Idea I had was you could make a quick simple GUI with pygame or tkinter or something! Please let me know what you wish to do to make it more complicated, then I will assign it to you!

**Comment by junyongxlee** [comment]
@Atharv-Attri I've never done any GUI on python but I believe this would be a good reason to learn, I'll need a few days to complete it as I may need some time to learn. If you're okay with that, I'm up for it!

**Comment by Atharv-Attri** [comment]
I'm perfectly fine with that! Quality over quantity!

**Comment by junyongxlee** [comment]
Great, please assign it to me! :)

**Comment by Atharv-Attri** [comment]
Done!
