### ISSUE TITLE
Project idea: Building Naive Bayes Classifier and Decision Tree Classifier from Scratch in Python (ML related stuff) 

### ISSUE THREAD

**Issue by shreyanshchordia** [Atharv-Attri/HacktoberFest-Projects#33]
### Describe your project idea here
Building ML algorithms NB Classifier and Decision Tree Classifier from scratch.

### What is a usage example of this? (We get somethings are pointless, yet still complex and fun to make, so we won't hold it against you if there is none.)

Checklist:
- [x] This has not been made in the language I want to make it in
- [x] I 100% believe this  meets quality standards

**Comment by shreyanshchordia** [comment]
Hey, please let me know if this is a good project to go with for your repository @Atharv-Attri

**Comment by Atharv-Attri** [comment]
Sorry for the late response, Yes! Absolutely! Go for it! I love this idea
