### ISSUE TITLE
File Organizer with GUI in Python

### ISSUE THREAD

**Issue by UsamaKashif** [Atharv-Attri/HacktoberFest-Projects#35]
File Organizer
This application is used to organize the files in a certain directory

A GUI application that allows you to select a folder and organize files in it by providing a folder name with file extensions that need to copied to that folder.

Made with Python and Tkinter.

**Comment by Atharv-Attri** [comment]
I have assigned it to you, go for it!

**Comment by UsamaKashif** [comment]
Thank you.
This will count for hacktober fest, right??

**Comment by Atharv-Attri** [comment]
Yes it will, once I merge it in
