### ISSUE TITLE
Project idea: <Console based Tic Tac Toe> in <Java>

### ISSUE THREAD

**Issue by Miqhtiedev** [Atharv-Attri/HacktoberFest-Projects#41]
### What is a usage example of this? (We get somethings are pointless, yet still complex and fun to make, so we won't hold it against you if there is none.)

Checklist:
- [ ] This has not been made in the language I want to make it in
- [ ] I 100% believe this  meets quality standards

**Comment by Atharv-Attri** [comment]
Will it be human against AI? If so, what algorithm will you use?
