### ISSUE TITLE
Project idea: Snake Game in Python

### ISSUE THREAD

**Issue by 10smruti** [Atharv-Attri/HacktoberFest-Projects#51]
### Describe your project idea here

Program to play the snake game which we used to play in childhood where the snake moves to eat the apple and once it eats, its length increases.
It will be having background music playing as well as a different sound when the snake dies or eats an apple.
It also shows the score of the user in the bottom.
We can convert it to a binary executable file.

### What is a usage example of this? (We get somethings are pointless, yet still complex and fun to make, so we won't hold it against you if there is none.)
- This is a fun game, but by designing this, one will learn a lot

Checklist:
- [x] This has not been made in the language I want to make it in
- [x] I 100% believe this  meets quality standards

**Comment by Atharv-Attri** [comment]
I'm all for it! Go ahead!
