### ISSUE TITLE
Project idea: Image to Sketch in Python

### ISSUE THREAD

**Issue by 10smruti** [Atharv-Attri/HacktoberFest-Projects#52]
### Describe your project idea here
Program to turn any image into a pencil sketch using OpenCV of image processing.

Checklist:
- [x] This has not been made in the language I want to make it in
- [x] I 100% believe this  meets quality standards

**Comment by Atharv-Attri** [comment]
I really like this idea. I do feel that this might be too simple, so I may tell you make it more complicated by adding a GUI or something, but first make the PR with just the base code, then I can go over the code and see if you need to add a GUI or something else to make it more complicated.
