### ISSUE TITLE
Project idea: Image to ASCII art converter in Python

### ISSUE THREAD

**Issue by volt9801** [Atharv-Attri/HacktoberFest-Projects#57]
### Describe your project idea here
The python script will have a function that will take the path to image as parameter, and convert it to ascii art which can then be copy pasted!
### What is a usage example of this? (We get somethings are pointless, yet still complex and fun to make, so we won't hold it against you if there is none.)
It has no particular use except, it can create really cool looking ascii art
Here's a [sample](https://pastebin.com/raw/ELZjJpmp).

Checklist:
- [x] This has not been made in the language I want to make it in
- [x] I 100% believe this  meets quality standards

**Comment by Atharv-Attri** [comment]
Go for it!
