### ISSUE TITLE
Project idea: MazeSolver in Javascript

### ISSUE THREAD

**Issue by Vyvy-vi** [Atharv-Attri/HacktoberFest-Projects#61]
### Describe your project idea here
A program to illustrate the use of A* algorithm to solve randomly generated maze.

### What is a usage example of this? (We get somethings are pointless, yet still complex and fun to make, so we won't hold it against you if there is none.)
This gives an intro to A* algorithm, which can be scaled up into hardware application, say a drone that can learn how to navigate a maze...
Moreover, this illustrates the higher efficiency of this as compared to simple backtracking.

Checklist:
- [] This has not been made in the language I want to make it in
- [x] I 100% believe this  meets quality standards

**Comment by Atharv-Attri** [comment]
Go for it!
