### ISSUE TITLE
Project idea: tic tac toe ai in python

### ISSUE THREAD

**Issue by NIK-99** [Atharv-Attri/HacktoberFest-Projects#62]
### Describe your project idea here
 A tic-tac-toe game where one player is human and the other is a computer which uses a min-max algorithm

### What is a usage example of this? (We get somethings are pointless, yet still complex and fun to make, so we won't hold it against you if there is none.)
This is a fun game, but by designing this, one will learn a lot about the min-max algorithm used in games
Checklist:
- [ yes] This has not been made in the language I want to make it in
- [yes ] I 100% believe this  meets quality standards

**Comment by Atharv-Attri** [comment]
Yes go for it!
