### ISSUE TITLE
Playfair Cipher in python

### ISSUE THREAD

**Issue by rockboy987** [Atharv-Attri/HacktoberFest-Projects#7]
Create a python function to encrypt a given string in caesar cipher with left/right shift of N

I would like to work on this

**Comment by Atharv-Attri** [comment]
I think Caesar Cipher might be too simple. What about something else like a [vigenere cipher](https://www.google.com/search?q=vigenere+cipher)

**Comment by rockboy987** [comment]
How about playfair cipher?

**Comment by Atharv-Attri** [comment]
sure!!!

**Comment by rockboy987** [comment]
Working on it! Please assign it to me :)

**Comment by Atharv-Attri** [comment]
Done!
